version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:14.15.4
    steps:
      - checkout
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - yarn-cached-packages-{{ checksum "yarn.lock" }}
      - run:
          name: install packages
          command: yarn install --immutable
      - save_cache:
          key: yarn-cached-packages-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Run Tests
          command: yarn test#
  build_and_save:
    docker:
      - image: cimg/node:14.15.4
    steps:
      - checkout
      - run: yarn build
      - store_artifacts:
          path: /bin/build

workflows:
  orb-free-workflow:
    jobs:
      - test
      - build_and_save
