version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:14.15.4
    steps:
      - checkout
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - yarn-cached-packages-{{ checksum "yarn.lock" }}
      - run:
          name: install packages
          command: yarn install --immutable
      - save_cache:
          key: yarn-cached-packages-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Run Tests
          command: yarn test
      - run: yarn build
      - store_artifacts:
          path: ./build
  publish-github-release:
    docker:
      - image: circleci/golang:1.10
    steps:
      - attach_workspace:
          at: ./build
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr

          
workflows:
  orb-free-workflow:
    jobs:
      - test
      - publish-github-release
