version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:14.15.4
    steps:
      - checkout
      - run:
          name: install packages
          command: yarn install
      - run:
          name: Run Tests
          command: yarn test


workflows:
  orb-free-workflow:
    jobs:
      - test
